name: proxinet
description: ProxiNet - privacy-first proximity networking
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^16.1.0
  get_it: ^8.2.0
  shared_preferences: ^2.2.2
  crypto: ^3.0.3
  flutter_secure_storage: ^9.0.0
  permission_handler: ^12.0.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  flutter_blue_plus: ^1.32.2
  google_sign_in: ^6.2.1
  googleapis: ^14.0.0
  oauth2: ^2.0.2
  sign_in_with_apple: ^6.1.1
  # flutter_twitter_login: ^1.0.0  # Outdated, requires null safety
  # linkedin_login: ^2.0.0  # Outdated, requires null safety
  flutter_map: ^8.2.1
  latlong2: ^0.9.0
  http: ^1.1.2
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  file_picker: ^10.3.1
  flutter_local_notifications: ^19.4.0
  uuid: ^4.4.0
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.1
  firebase_messaging: ^16.0.0
  firebase_storage: ^13.0.0
  csv: ^6.0.0
  flutter_ble_peripheral: ^1.2.6
  cloud_functions: ^6.0.0
  share_plus: ^7.2.1
  url_launcher: ^6.2.4
  # contacts_service: ^0.6.3  # Outdated, has Android compatibility issues

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
